version: '3.0'
services:
  postgresql:
    image: postgres:17.5
    container_name: postgresql
    hostname: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: OrderDB
    networks:
      - keycloak
  mongodb:
    image: mongo:8.0-rc
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: PaymentDB
  redis:
    image: redis:8.0-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=1234
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      - es
  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      SERVER_NAME: kibana
    depends_on:
      - elasticsearch
    networks:
      - es
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    hostname: kafka
    ports:
      - "10001:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_PROCESS_ROLES: 'controller, broker'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://kafka1:10001
      ALLOW_PLAINTEXT_LISTENERS: yes
      CLUSTER_ID: Z2l2ZW1lc3RyZW5ndGg
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.4
    ports:
      - "8090:8080"
    command:
      - "start-dev"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/OrderDB
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 1234
    depends_on:
      - postgresql
    networks:
      - keycloak

networks:
  es:
    driver: bridge
  keycloak:
    driver: bridge
