spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  application:
    name: api-gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5432/ApiGateway
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/OrderDB?authSource=admin
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
  elasticsearch:
    uris: http://localhost:9200
    password: 1234
  kafka:
    bootstrap-servers: localhost:9101
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: API-GATEWAY
      auto-offset-reset: earliest
  cloud:
    config:
      enabled: false
    gateway:
      enabled: true
      routes:
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-resilience
                fallbackUri: forward:/fallback

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/oauth2

---
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    status-page-url-path: /api/info
    health-check-url-path: /api/health
---

---
# resilience4j
resilience4j:
  ratelimiter:
    instances:
      payment-service-resilience:
        limit-for-period: 10
        limit-refresh-period:
          seconds: 5
        timeout-duration:
          seconds: 2
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      payment-service-resilience:
        base-config: default

---

---
# logging
logging:
  level:
    org.springframework.cloud: DEBUG
---

---
# kafka
kafka:
  schema-registry-url: http://localhost:8085
schema.registry.url: http://localhost:8085
---

# port
server:
  port: 8082