name: Payment-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:23.0.3
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Containers For Payment Service
        run: docker compose -f docker-compose-payment-service.yml up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run Tests with Coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: payment-service/build/reports/jacoco/test/html

      - name: Upload Problem Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: problems-report
          path: payment-service/build/reports/problems/problems-report.html

      - name: Add Coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60